In [1]:
import tensorflow as tf

Tensors are multi-dimensional arrays

In [2]:
a = tf.constant(4)

In [3]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=4>

A tensor can be converted to a numpy object (constant or array)

In [4]:
a.numpy()

4

In [5]:
type(a.numpy())

numpy.int32

Tensors can also be like arrays

In [6]:
b = tf.constant([2.5, 5])

In [7]:
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.5, 5. ], dtype=float32)>

In [8]:
b.numpy()

array([2.5, 5. ], dtype=float32)

Numpy arrays can also be converted to tensors!

In [9]:
import numpy as np

In [10]:
c = np.array([1,2,3])

In [11]:
c

array([1, 2, 3])

In [12]:
tf.constant(c)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

You can address the elements of a tensor very easily

In [13]:
b[0]

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [14]:
d = tf.constant(np.random.rand(2,3,4))

In [15]:
d

<tf.Tensor: shape=(2, 3, 4), dtype=float64, numpy=
array([[[0.04184026, 0.33861261, 0.6069483 , 0.40319058],
        [0.29298756, 0.61918765, 0.22444237, 0.95359099],
        [0.10677458, 0.98853865, 0.57426351, 0.33778053]],

       [[0.22794782, 0.84059477, 0.49273727, 0.61589484],
        [0.68170838, 0.56747572, 0.17121941, 0.05120123],
        [0.29804877, 0.41531444, 0.20225711, 0.11965733]]])>

Note that the shape of a tensor is similar to the shape of a numpy array

In [16]:
d.shape

TensorShape([2, 3, 4])

In [17]:
d[:, 2, 1]

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.98853865, 0.41531444])>

In [18]:
d[1, :, :]

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.22794782, 0.84059477, 0.49273727, 0.61589484],
       [0.68170838, 0.56747572, 0.17121941, 0.05120123],
       [0.29804877, 0.41531444, 0.20225711, 0.11965733]])>

You can also reshape a tensor!

In [19]:
tf.reshape(d, (1,24))

<tf.Tensor: shape=(1, 24), dtype=float64, numpy=
array([[0.04184026, 0.33861261, 0.6069483 , 0.40319058, 0.29298756,
        0.61918765, 0.22444237, 0.95359099, 0.10677458, 0.98853865,
        0.57426351, 0.33778053, 0.22794782, 0.84059477, 0.49273727,
        0.61589484, 0.68170838, 0.56747572, 0.17121941, 0.05120123,
        0.29804877, 0.41531444, 0.20225711, 0.11965733]])>

In [20]:
tf.reshape(d, (-1, 2, 6))

<tf.Tensor: shape=(2, 2, 6), dtype=float64, numpy=
array([[[0.04184026, 0.33861261, 0.6069483 , 0.40319058, 0.29298756,
         0.61918765],
        [0.22444237, 0.95359099, 0.10677458, 0.98853865, 0.57426351,
         0.33778053]],

       [[0.22794782, 0.84059477, 0.49273727, 0.61589484, 0.68170838,
         0.56747572],
        [0.17121941, 0.05120123, 0.29804877, 0.41531444, 0.20225711,
         0.11965733]]])>

The type of a tensor can be changed!

In [21]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [22]:
tf.cast(a, tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=4.0>

Tensors can be multiplied by each other

In [23]:
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.5, 5. ], dtype=float32)>

element-wise

In [24]:
tf.multiply(b,b)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.25, 25.  ], dtype=float32)>

In [25]:
b*b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.25, 25.  ], dtype=float32)>

In [26]:
tf.transpose(b)*b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.25, 25.  ], dtype=float32)>

In [27]:
tf.math.multiply(b,b)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6.25, 25.  ], dtype=float32)>

Like Matrix multiplication

In [28]:
x = tf.random.normal((3,4))

In [29]:
x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.9607608 , -0.35646817,  0.93900687,  0.4161086 ],
       [ 0.71798944,  0.77688843,  0.02356884, -0.4745757 ],
       [ 1.3081326 , -1.090956  ,  1.433547  ,  0.09774182]],
      dtype=float32)>

In [30]:
y = tf.random.normal((4,5))

In [31]:
y

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.99394184,  0.33136567, -0.50802565,  0.36493453, -0.10026028],
       [ 1.6389345 ,  0.5094567 , -0.5023374 , -0.02546229,  1.4222236 ],
       [-0.3222886 ,  0.70820916,  0.15140133, -1.9902506 ,  0.6120796 ],
       [ 0.854737  , -1.3451148 , -0.32620043,  0.55723816, -0.78872275]],
      dtype=float32)>

In [32]:
x*y

InvalidArgumentError: ignored

In [33]:
tf.transpose(x)*y

InvalidArgumentError: ignored

In [34]:
tf.multiply(x,y)

InvalidArgumentError: ignored

In [35]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-2.480078  ,  0.57342315, -0.8106174 , -0.9123615 , -0.45701122],
       [ 0.14639622,  1.2887586 , -0.596642  , -0.06912181,  1.4216579 ],
       [-3.4666853 ,  0.7614526 ,  0.06862059, -2.2934914 , -0.88238335]],
      dtype=float32)>

In [36]:
p = tf.random.normal((2,3,4))
q = tf.random.normal((2,4,5))

In [37]:
tf.matmul(p,q)

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[ 1.3760768 ,  2.209335  , -1.5591226 , -1.2694542 ,
         -1.8127143 ],
        [ 1.7660447 ,  2.241684  , -2.8010824 ,  1.1856338 ,
         -3.2843149 ],
        [-0.63371503,  0.05840356, -0.6862974 ,  0.9873891 ,
         -1.0893885 ]],

       [[ 0.22890003, -0.9217443 ,  1.7529117 , -1.8931926 ,
          2.3079977 ],
        [ 0.0267887 ,  1.1989231 ,  0.29417646,  1.0889169 ,
         -1.9836926 ],
        [ 1.930299  , -0.5267614 , -2.9848726 ,  3.0073903 ,
         -6.677432  ]]], dtype=float32)>

In [38]:
v = tf.random.normal((2,3,4))
w = tf.random.normal((3,4,5))

In [39]:
tf.matmul(v,w)

InvalidArgumentError: ignored

In [40]:
e = tf.random.normal((2,3,4,5))
f = tf.random.normal((2,3,5,6))

In [41]:
e*f

InvalidArgumentError: ignored

In [42]:
tf.matmul(e,f)

<tf.Tensor: shape=(2, 3, 4, 6), dtype=float32, numpy=
array([[[[-3.2705836e+00,  3.5582751e-01, -8.4884155e-01,
          -3.5772367e+00,  1.0045640e+00,  3.7406113e+00],
         [ 6.2106013e+00, -1.2557305e+00, -3.0656848e+00,
           3.4296176e-01, -1.3073492e+00, -8.9618425e+00],
         [-5.2061620e+00,  7.3561770e-01, -3.5322678e-01,
          -3.9014559e+00,  1.4710505e+00,  6.6329732e+00],
         [-2.3730903e+00,  3.0079815e-03, -1.3620129e+00,
          -3.2412827e+00,  1.6233550e+00,  2.2768815e+00]],

        [[-4.0673466e+00, -2.3363712e+00, -1.4207942e+00,
           3.0571885e+00,  8.0452557e+00,  6.2772655e-01],
         [-1.5088892e+00,  1.6458896e+00, -2.6573405e+00,
          -1.8228742e+00,  2.9173350e+00, -8.3595067e-01],
         [ 2.1332405e+00, -2.4523811e+00,  4.5454926e+00,
           4.1244898e+00, -4.8664694e+00,  2.4628432e+00],
         [ 6.9556755e-01, -5.1462382e-01, -9.6677206e-03,
           6.5193847e-02,  2.2598560e-01, -8.2582317e-02]],

      

Tensors can be added to each other

In [43]:
g = tf.random.uniform((3,5))
h = tf.random.uniform((3,5))

In [44]:
g+h

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1.1050751 , 1.5247577 , 0.406924  , 1.5999191 , 1.4988637 ],
       [1.1051204 , 1.4660577 , 0.92646444, 0.6567985 , 0.92431355],
       [1.0663185 , 1.0878391 , 0.53074074, 1.4415329 , 0.7878362 ]],
      dtype=float32)>

In [45]:
tf.add(g,h)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1.1050751 , 1.5247577 , 0.406924  , 1.5999191 , 1.4988637 ],
       [1.1051204 , 1.4660577 , 0.92646444, 0.6567985 , 0.92431355],
       [1.0663185 , 1.0878391 , 0.53074074, 1.4415329 , 0.7878362 ]],
      dtype=float32)>